version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3310:3306"

